// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/recommendation/proto/recommendation.proto

package recommendation

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The requirement of the recommendation.
type Request struct {
	Require              string   `protobuf:"bytes,1,opt,name=require,proto3" json:"require,omitempty"`
	Lat                  float64  `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                  float64  `protobuf:"fixed64,3,opt,name=lon,proto3" json:"lon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdc08925ee391d99, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetRequire() string {
	if m != nil {
		return m.Require
	}
	return ""
}

func (m *Request) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Request) GetLon() float64 {
	if m != nil {
		return m.Lon
	}
	return 0
}

type Result struct {
	HotelIds             []string `protobuf:"bytes,1,rep,name=HotelIds,proto3" json:"HotelIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdc08925ee391d99, []int{1}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetHotelIds() []string {
	if m != nil {
		return m.HotelIds
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "recommendation.Request")
	proto.RegisterType((*Result)(nil), "recommendation.Result")
}

func init() {
	proto.RegisterFile("services/recommendation/proto/recommendation.proto", fileDescriptor_fdc08925ee391d99)
}

var fileDescriptor_fdc08925ee391d99 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0xcf, 0xb1, 0x8a, 0x83, 0x40,
	0x10, 0x06, 0x60, 0xf6, 0x04, 0x3d, 0xa7, 0x90, 0x63, 0x8b, 0xcb, 0x62, 0x25, 0x92, 0xc2, 0x4a,
	0xc1, 0x3c, 0x43, 0x30, 0x69, 0xb7, 0x49, 0x6d, 0x74, 0x0a, 0x41, 0x77, 0xe2, 0xee, 0x98, 0xe7,
	0x0f, 0x8a, 0x09, 0x68, 0xba, 0xf9, 0xbf, 0x29, 0xe6, 0x1f, 0x28, 0x1d, 0xda, 0x67, 0xd7, 0xa0,
	0x2b, 0x2c, 0x36, 0x34, 0x0c, 0x68, 0xda, 0x9a, 0x3b, 0x32, 0xc5, 0xc3, 0x12, 0xd3, 0x0e, 0xf3,
	0x05, 0x65, 0xb4, 0xd5, 0xb4, 0x82, 0x40, 0xe3, 0x38, 0xa1, 0x63, 0xa9, 0x20, 0xb0, 0x38, 0x4e,
	0x9d, 0x45, 0x25, 0x12, 0x91, 0x85, 0xfa, 0x1d, 0xe5, 0x1f, 0x78, 0x7d, 0xcd, 0xea, 0x27, 0x11,
	0x99, 0xd0, 0xf3, 0xb8, 0x08, 0x19, 0xe5, 0xad, 0x42, 0x26, 0x3d, 0x82, 0xaf, 0xd1, 0x4d, 0x3d,
	0xcb, 0x18, 0x7e, 0x2f, 0xc4, 0xd8, 0x5f, 0x5b, 0xa7, 0x44, 0xe2, 0x65, 0xa1, 0xfe, 0xe4, 0xf2,
	0x06, 0x91, 0xde, 0x14, 0x90, 0x67, 0x90, 0x15, 0xf2, 0x16, 0x9d, 0x3c, 0xe4, 0xbb, 0xf6, 0x6b,
	0xc9, 0xf8, 0xff, 0x7b, 0x31, 0x1f, 0xbd, 0xfb, 0xcb, 0x7b, 0xa7, 0x57, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x02, 0xb5, 0xe4, 0x18, 0x14, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RecommendationClient is the client API for Recommendation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RecommendationClient interface {
	// GetRecommendations returns recommended hotels for a given requirement
	GetRecommendations(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Result, error)
}

type recommendationClient struct {
	cc grpc.ClientConnInterface
}

func NewRecommendationClient(cc grpc.ClientConnInterface) RecommendationClient {
	return &recommendationClient{cc}
}

func (c *recommendationClient) GetRecommendations(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/recommendation.Recommendation/GetRecommendations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecommendationServer is the server API for Recommendation service.
type RecommendationServer interface {
	// GetRecommendations returns recommended hotels for a given requirement
	GetRecommendations(context.Context, *Request) (*Result, error)
}

// UnimplementedRecommendationServer can be embedded to have forward compatible implementations.
type UnimplementedRecommendationServer struct {
}

func (*UnimplementedRecommendationServer) GetRecommendations(ctx context.Context, req *Request) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecommendations not implemented")
}

func RegisterRecommendationServer(s *grpc.Server, srv RecommendationServer) {
	s.RegisterService(&_Recommendation_serviceDesc, srv)
}

func _Recommendation_GetRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendationServer).GetRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/recommendation.Recommendation/GetRecommendations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendationServer).GetRecommendations(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Recommendation_serviceDesc = grpc.ServiceDesc{
	ServiceName: "recommendation.Recommendation",
	HandlerType: (*RecommendationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRecommendations",
			Handler:    _Recommendation_GetRecommendations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/recommendation/proto/recommendation.proto",
}
