version: "3"
services:
  consul:
    image: consul:1.12
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  frontend:
    environment:
      - TLS
      - GC
      - JAEGER_SAMPLE_RATIO
      - LOG_LEVEL
    image: mwotila/hotel_reserv_frontend_single_node:latest
    entrypoint: frontend
    container_name: 'hotel_reserv_frontend'
    ports:
      - "5000:5000"
    depends_on:
      - consul
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  profile:
    environment:
      - TLS
      - GC
      - JAEGER_SAMPLE_RATIO
      - MEMC_TIMEOUT
      - LOG_LEVEL
    image: mwotila/hotel_reserv_profile_single_node:latest
    entrypoint: profile
    container_name: 'hotel_reserv_profile'
    depends_on:
      - mongodb-profile
      - memcached-profile
      - consul
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  search:
    image: mwotila/hotel_reserv_search_single_node:latest
    entrypoint: search
    container_name: 'hotel_reserv_search'
    depends_on:
      - consul
    environment:
      - TLS
      - GC
      - JAEGER_SAMPLE_RATIO
      - LOG_LEVEL
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  geo:
    environment:
      - TLS
      - GC
      - JAEGER_SAMPLE_RATIO
      - LOG_LEVEL
    image: mwotila/hotel_reserv_geo_single_node:latest
    entrypoint: geo
    container_name: 'hotel_reserv_geo'
    depends_on:
      - mongodb-geo
      - consul
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  rate:
    environment:
      - TLS
      - GC
      - JAEGER_SAMPLE_RATIO
      - LOG_LEVEL
      - MEMC_TIMEOUT      
    image: mwotila/hotel_reserv_rate_single_node:latest
    entrypoint: rate
    container_name: 'hotel_reserv_rate'
    depends_on:
      - mongodb-rate
      - memcached-rate
      - consul
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  recommendation:
    environment:
      - TLS
      - GC
      - JAEGER_SAMPLE_RATIO
      - LOG_LEVEL
    image: mwotila/hotel_reserv_recommend_single_node:latest
    entrypoint: recommendation
    container_name: 'hotel_reserv_recommendation'
    depends_on:
      - mongodb-recommendation
      - consul
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  user:
    environment:
      - TLS
      - GC
      - JAEGER_SAMPLE_RATIO
      - LOG_LEVEL
    image: mwotila/hotel_reserv_user_single_node:latest
    entrypoint: user
    container_name: 'hotel_reserv_user'
    depends_on:
      - mongodb-user
      - consul
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  reservation:
    environment:
      - TLS
      - GC
      - JAEGER_SAMPLE_RATIO
      - LOG_LEVEL
      - MEMC_TIMEOUT
    image: mwotila/hotel_reserv_rsv_single_node:latest
    entrypoint: reservation
    container_name: 'hotel_reserv_reservation'
    depends_on:
      - mongodb-reservation
      - memcached-reserve
      - consul
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  memcached-rate:
    image: memcached
    container_name: 'hotel_reserv_rate_mmc'
    environment:
      - MEMCACHED_CACHE_SIZE=128
      - MEMCACHED_THREADS=2
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  memcached-profile:
    image: memcached
    container_name: 'hotel_reserv_profile_mmc'
    environment:
      - MEMCACHED_CACHE_SIZE=128
      - MEMCACHED_THREADS=2
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  memcached-reserve:
    image: memcached
    container_name: 'hotel_reserv_reservation_mmc'
    environment:
      - MEMCACHED_CACHE_SIZE=128
      - MEMCACHED_THREADS=2
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  mongodb-geo:
    image: mongo:4.4.6
    container_name: 'hotel_reserv_geo_mongo'
    volumes:
      - geo:/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  mongodb-profile:
    image: mongo:4.4.6
    container_name: 'hotel_reserv_profile_mongo'
    volumes:
      - profile:/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  mongodb-rate:
    image: mongo:4.4.6
    container_name: 'hotel_reserv_rate_mongo'
    volumes:
      - rate:/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  mongodb-recommendation:
    image: mongo:4.4.6
    container_name: 'hotel_reserv_recommendation_mongo'
    volumes:
      - recommendation:/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  mongodb-reservation:
    image: mongo:4.4.6
    container_name: 'hotel_reserv_reservation_mongo'
    volumes:
      - reservation:/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  mongodb-user:
    image: mongo:4.4.6
    container_name: 'hotel_reserv_user_mongo'
    volumes:
      - user:/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  jaeger:
    image: jaegertracing/all-in-one:1.25
    container_name: 'hotel_reserv_jaeger'
    ports:
      - "14250:14250"
      - "9411:9411"
      - "14269"
      - "5778:5778"
      - "14268:14268"
      - "14267"
      - "16686:16686"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"  
    environment:
      - JAEGER_DISABLED=true
      - SPAN_STORAGE_TYPE=grpc-plugin
      - GRPC_STORAGE_PLUGIN_BINARY=/app/jaeger-mongodb
      - GRPC_STORAGE_PLUGIN_CONFIGURATION_FILE=/app/configs/config.yaml
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints: [node.role == manager]
    volumes:
      #- /home/ubuntu/ocas/jaeger-mongodb:/app
      - /proj/rip-PG0/ocas/jaeger-mongodb:/app

volumes:
  geo:
  profile:
  rate:
  recommendation:
  reservation:
  user: