version: "3"
services:
  frontend:
    environment:
      - TLS
      - GC
      - JAEGER_SAMPLE_RATIO
      - LOG_LEVEL
    image: hotel_reserv_frontend_single_node:latest
    entrypoint: frontend
    container_name: 'hotel_reserv_frontend'
    ports:
      - "5000:5000"
    #depends_on:
    #  - consul
    deploy:
      replicas: 3
      restart_policy:
        condition: any
    logging:
      driver: "fluentd"
      options:
        tag: "frontend"