version: "3"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: 'hotel_reserv_jaeger'
    ports:
      - "14250:14250"
      - "9411:9411"
      - "14269"
      - "5778:5778"
      - "14268:14268"
      - "14267"
      - "16686:16686"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"  
    environment:
      - JAEGER_DISABLED="true"
      # SPAN_STORAGE_TYPE: "grpc-plugin"
      # GRPC_STORAGE_PLUGIN_BINARY: "/app/jaeger-mongodb"
      # GRPC_STORAGE_PLUGIN_CONFIGURATION_FILE: "/app/configs/config.yaml"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints: [node.role == manager]
    volumes:
      - /home/ubuntu/ocas/jaeger-mongodb:/app