cluster:
  nodes:
    - id: "1"
      name: "cr-jhb"
      ip: "129.232.230.130"
    - id: "2"
      name: "cr-dar"
      ip: "196.32.212.213"
    - id: "3"
      name: "cr-kla"
      ip: "102.134.147.244"
    - id: "4"
      name: "cr-lsk"
      ip: "196.32.215.213"
    - id: "5"
      name: "cr-bun"
      ip: "196.43.171.248"
  prometheus:
    url: "http://cr.cranecloud.africa:9090"
    label: "container_label_com_docker_swarm_service_name"
    stack: "hotelreservation_"
    query: "sum(rate(metric{container_label_com_docker_swarm_service_name=\"_\"}[2m])) by (instance)" # query to get nodes
    metric: "container_cpu_usage_seconds_total" # metric to determine service node

database:
  uri: "mongodb://mongoadmin:949cad0977fb8daf334e@cr.cranecloud.africa:27017/"
  db: "yonga"
  collections:
    # - name: "host"
    # - name: "environment"
    # - name: "service"
    # - name: "trace"
    - name: "cr-jhb"
    - name: "cr-dar"
    - name: "cr-kla"
    - name: "cr-lsk"
    - name: "cr-bun"

services:
  - name: "frontend"
    id: "1"
    cache: ""
    db: ""
  - name: "profile"
    id: "2"
    cache: "memcached-profile"
    db: "mongodb-profile"
  - name: "search"
    id: "3"
    cache: ""
    db: ""
  - name: "geo"
    id: "4"
    cache: ""
    db: "mongodb-geo"
  - name: "rate"
    id: "5"
    cache: "memcached-rate"
    db: "mongodb-rate"
  - name: "recommendation"
    id: "6"
    cache: ""
    db: "mongodb-recommendation"
  - name: "user"
    id: "7"
    cache: ""
    db: "mongodb-user"
  - name: "reservation"
    id: "8"
    cache: "memcached-reserve"
    db: "mongodb-reservation"
  - name: "memcached-rate"
    id: "9"
    cache: ""
    db: ""
  - name: "memcached-profile"
    id: "10"
    cache: ""
    db: ""
  - name: "memcached-reserve"
    id: "11"
    cache: ""
    db: ""
  - name: "mongodb-geo"
    id: "12"
    cache: ""
    db: ""
  - name: "mongodb-profile"
    id: "13"
    cache: ""
    db: ""
  - name: "mongodb-rate"
    id: "14"
    cache: ""
    db: ""
  - name: "mongodb-recommendation"
    id: "15"
    cache: ""
    db: ""
  - name: "mongodb-reservation"
    id: "16"
    cache: ""
    db: ""
  - name: "mongodb-user"
    id: "17"
    cache: ""
    db: ""