cluster:
  nodes:
    - id: "1"
      name: "cr-jhb"
      ip: "129.232.230.130"
      resource: 
        cpu: 16
        memory: 64317
        disk: 1800000
        network: 1000
    - id: "2"
      name: "cr-dar"
      ip: "196.32.212.213"
      resource: 
        cpu: 2
        memory: 16000
        disk: 245000
        network: 1000
    - id: "3"
      name: "cr-kla"
      ip: "102.134.147.244"
      resource: 
        cpu: 2
        memory: 16000
        disk: 47000
        network: 1000
    - id: "4"
      name: "cr-lsk"
      ip: "196.32.215.213"
      resource: 
        cpu: 2
        memory: 16000
        disk: 245000
        network: 1000
    - id: "5"
      name: "cr-bun"
      ip: "196.43.171.248"
      resource: 
        cpu: 2
        memory: 16000
        disk: 194000
        network: 1000
  prometheus:
    url: "http://196.32.213.62:9090"
    label: "container_label_com_docker_swarm_service_name"
    stack: "hotelreservation_"
    query: "sum(rate(metric{container_label_com_docker_swarm_service_name=\"_\"}[2m])) by (instance)" # query to get nodes
    metric: "container_cpu_usage_seconds_total" # metric to determine service node


database:
  uri: "mongodb://mongoadmin:949cad0977fb8daf334e@196.32.213.62:27017/"
  db: "yonga"
  collections:
    # - name: "trace"
    - name: "cr-jhb"
    - name: "cr-dar"
    - name: "cr-kla"
    - name: "cr-lsk"
    - name: "cr-bun"

services:
  - name: "frontend"
    id: "1"
    cache: ""
    db: ""
  - name: "profile"
    id: "2"
    cache: "memcached-profile"
    db: "mongodb-profile"
  - name: "search"
    id: "3"
    cache: ""
    db: ""
  - name: "geo"
    id: "4"
    cache: ""
    db: "mongodb-geo"
  - name: "rate"
    id: "5"
    cache: "memcached-rate"
    db: "mongodb-rate"
  - name: "recommendation"
    id: "6"
    cache: ""
    db: "mongodb-recommendation"
  - name: "user"
    id: "7"
    cache: ""
    db: "mongodb-user"
  - name: "reservation"
    id: "8"
    cache: "memcached-reserve"
    db: "mongodb-reservation"
  - name: "memcached-rate"
    id: "9"
    cache: ""
    db: ""
  - name: "memcached-profile"
    id: "10"
    cache: ""
    db: ""
  - name: "memcached-reserve"
    id: "11"
    cache: ""
    db: ""
  - name: "mongodb-geo"
    id: "12"
    cache: ""
    db: ""
  - name: "mongodb-profile"
    id: "13"
    cache: ""
    db: ""
  - name: "mongodb-rate"
    id: "14"
    cache: ""
    db: ""
  - name: "mongodb-recommendation"
    id: "15"
    cache: ""
    db: ""
  - name: "mongodb-reservation"
    id: "16"
    cache: ""
    db: ""
  - name: "mongodb-user"
    id: "17"
    cache: ""
    db: ""

weights:
  - name: "cpu"
    value: 0.4
  - name: "memory"
    value: 0.3
  - name: "disk"
    value: 0.2
  - name: "network"
    value: 0.1
  - name: "latency"
    value: 0.4
  - name: "available"
    value: 0.2
  - name: "bandwidth"
    value: 0.3
  - name: "packet_loss"
    value: 0.1